// Encodes the hero clip from public/footage/hero-source.mp4 (an 8 s aerial
// shot of a grey Cascadia, generated by the owner) into ../public/hero:
//   truck-reveal.{mp4,webm}   5 s: the first 6.25 s at 1.25× speed, no audio.
//                             ≤5 s and plays once, so no pause control is
//                             needed (WCAG 2.2.2).
//   truck-reveal-first.jpg    poster (first frame)
//   truck-reveal-last.jpg     still for reduced motion / Data Saver (last frame)
//   truck-reveal-backdrop.jpg small, blurred last frame the desktop hero sits
//                             the sharp video window on
// Uses the system ffmpeg (libx264 + libvpx-vp9). Run by render.mjs.
import { execFileSync } from 'node:child_process';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.join(here, 'public', 'footage', 'hero-source.mp4');
const out = path.join(here, '..', 'public', 'hero');

const SPEED = 1.25;
const SECONDS = 5;
// Light grade to sit with the site: a touch more contrast, slightly warmer.
const GRADE = 'eq=contrast=1.05:saturation=1.06,colorbalance=rs=0.02:bs=-0.02';
const TIMING = `setpts=PTS/${SPEED},fps=30`;

const ff = (args) => execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', ...args], { stdio: 'inherit' });

export function encodeHero() {
  mkdirSync(out, { recursive: true });
  const vf = `${TIMING},${GRADE},format=yuv420p`;
  ff(['-i', src, '-an', '-vf', vf, '-t', String(SECONDS), '-c:v', 'libx264', '-crf', '23', '-preset', 'veryslow', '-movflags', '+faststart', path.join(out, 'truck-reveal.mp4')]);
  ff(['-i', src, '-an', '-vf', vf, '-t', String(SECONDS), '-c:v', 'libvpx-vp9', '-crf', '38', '-b:v', '0', '-row-mt', '1', '-deadline', 'good', '-cpu-used', '1', path.join(out, 'truck-reveal.webm')]);
  const still = (at, file, extra = '') =>
    ff(['-ss', String(at), '-i', src, '-frames:v', '1', '-vf', `${GRADE}${extra}`, '-q:v', '3', path.join(out, file)]);
  const lastAt = (SECONDS - 1 / 30) * SPEED;
  still(0, 'truck-reveal-first.jpg');
  still(lastAt, 'truck-reveal-last.jpg');
  still(lastAt, 'truck-reveal-backdrop.jpg', ',scale=640:-2,gblur=sigma=14');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  encodeHero();
  console.log('hero encoded');
}
